# OPAL data Fuseki
#
# Basic Fuseki Dockerfile to extend later.
#
# Configuration of the base image is described here:
#  https://hub.docker.com/r/stain/jena-fuseki
#
# Check the latest available Fuseki version:
#  https://jena.apache.org/download/

FROM stain/jena-fuseki:3.10.0
