# OPAL data Fuseki
# 
# Repository:
# https://github.com/projekt-opal/opaldata
#
# Based on:
# https://hub.docker.com/r/stain/jena-fuseki

version: '3.2'

services:

  opal-fuseki:
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${FUSEKI_JVM_ARGS}
    ports:
      - 3030:3030
    build:
      ./
    volumes:
      - fuseki-data:/fuseki

volumes:
  fuseki-data:
