# OPAL data Fuseki
# 
# Repository:
# https://github.com/projekt-opal/opaldata
#
# Based on:
# https://hub.docker.com/r/stain/jena-fuseki
#
# Databases require prefix 'FUSEKI_DATASET_'
# https://github.com/stain/jena-docker/issues/33

version: '3.2'

services:

  opal-fuseki:
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${FUSEKI_JVM_ARGS}
      - FUSEKI_DATASET_1=opal-2020-04
      - FUSEKI_DATASET_2=opal-2020-07
    ports:
      - 3030:3030
    build:
      ./
    volumes:
      - fuseki-data:/fuseki

volumes:
  fuseki-data:
