# OPAL data
#
# Configurations are described in the subfolders.

version: '3.2'

services:

### Elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
      - discovery.type=single-node
    volumes:
      - esdata01:/usr/share/elasticsearch/data
  elasticsearch-mapping-init:
    build: elasticsearch/
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

### Fuseki

  opal-fuseki:
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${FUSEKI_JVM_ARGS}
    ports:
      - 3030:3030
    build:
      fuseki/
    volumes:
      - fuseki-data

### Overall volumes

volumes:
  fuseki-data:
  esdata01:
