# OPAL data
#
# Configuration is described in the subfolders.

version: '3'

services:
  opal-fuseki:
    container_name: opal-fuseki
    environment:
      - JVM_ARGS=-Xmx2g
      - ADMIN_PASSWORD=opalfuseki
    ports:
      - 3030:3030
    build:
      fuseki/
