# OPAL data
#
# Configurations are described in the subfolders.

version: '3.2'

services:

### Elasticsearch

  elasticsearch:
    build: elasticsearch
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data

  elasticsearch-initialization:
    build: elasticsearch-initialization
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

### Fuseki

  opal-fuseki:
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${FUSEKI_JVM_ARGS}
    ports:
      - 3030:3030
    build:
      fuseki/
    volumes:
      - fuseki-data:/fuseki

### Overall volumes

volumes:
  fuseki-data:
  esdata01:
