# OPAL data Elasticsearch
# 
# Repository:
# https://github.com/projekt-opal/opaldata

version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
  elasticsearch-mapping-init:
    build: ./
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
