# OPAL data Elasticsearch
# 
# Repository:
# https://github.com/projekt-opal/opaldata

FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.2
# FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.3
