# OPAL data Elasticsearch
# 
# Repository:
# https://github.com/projekt-opal/opaldata
#
# memory_lock ; ulimits: memlock: soft: -1 ; hard: -1
# https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docker.html

version: '3.2'
services:
  elasticsearch:
    build: ./
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data

  elasticsearch-initialization:
    build: ../elasticsearch-initialization/
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

volumes:
  esdata01:
