# OPAL data Elasticsearch
# 
# Repository:
# https://github.com/projekt-opal/opaldata

version: '3.2'
services:
  elasticsearch:
    build: ./
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
      - discovery.type=single-node
    volumes:
      - esdata01:/usr/share/elasticsearch/data

  elasticsearch-initialization:
    build: ../elasticsearch-initialization/
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

volumes:
  esdata01:
