# OPAL data Elasticsearch
# 
# Repository:
# https://github.com/projekt-opal/opaldata

version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
      - discovery.type=single-node
  elasticsearch-mapping-init:
    build: ./
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
